[build]
    command = "npm run build"
    functions = "functions"
    publish = "dist"

[[redirects]]
  from = "/api/v1/*"
  to = "/.netlify/functions/app"
  status = 200

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200